set-option -g prefix C-a
bind-key a send-prefix
bind-key C-a last-window
bind-key Space next-window
bind-key k confirm-before kill-pane

## status:
set-option -g status-style fg='#00aa00'
set-option -g status-left-length 10
set-option -g status-left '#[fg=gray][#[fg=color13]#I.#P#[fg=gray]] '
set-option -g status-right '#[fg=gray][#[fg=color13]%d/%m %H:%M %Z#[fg=gray]]'
set -g window-status-current-style 'bold,underscore'

%if #{==:#{host},x220.local}
   set-option -g status-right "#[fg=black]#(sysctl dev.cpu.0.freq | cut -d: -f2-)MHz #(sysctl hw.acpi.thermal.tz0.temperature | cut -d: -f2-)#[fg=colour238] #(acpiconf -i0 | grep Rem.*capacity | cut -d: -f2-) #[fg=colour250]%H:%M"
%endif

## bindings
bind-key m command-prompt -p 'man' "split-window 'exec man %%'"
bind-key r source-file ~/etc/tmux.conf
bind-key s split-window
bind-key S split-window -h

## message-bar:
set-option -g message-style bg=yellow,fg=black,bold

## panes:
set-option -g pane-border-style fg=darkgray
set-option -g pane-active-border-style fg=green

## misc
set-option -g display-time 2000
set-option -g mouse on
set-option -g update-environment "DISPLAY http_proxy ftp_proxy"
set -g base-index 1
