## hey emacs, this is kinda -*- sh -*- file
--cookies-from-browser=safari
--no-playlist
--mark-watched
--sponsorblock-mark=all
--write-auto-subs
--sub-langs="-all,..-orig"
--compat-options no-keep-subs
--embed-subs
--embed-chapters
--embed-thumbnail
--merge-output-format=mp4
--force-keyframes-at-cuts
--fragment-retries=200
--retry-sleep=fragment:exp=1:256
--retry-sleep=extractor:linear=1:10
--paths="subtitle:~/video/subs"
--paths="temp:/tmp"
--paths="~/video"
--output="%(title)s_[%(id|display_id|NA)s].%(ext)s"
--restrict-filenames
--1080p

## aliases
--alias=no-subs		"--no-write-subs --no-write-auto-subs"
--alias=only-auto-subs	"--no-embed-thumbnail --skip-download"
--alias=-Q              "--abort-on-unavailable-fragments"
--alias=aria2c		"--downloader='aria2c' --downloader-args='aria2c:-j4 -t20'"

# +vcodec:avc sets the video codec preference to h264 > h265 > vp9 >
# vp9.2 > av01 > vp8 > h263 > theora.
--alias=1080p --format-sort=res:1080,fps,ext:mp4,+vcodec:avc
--alias=720p  --format-sort=res:720,fps,ext:mp4,+vcodec:avc
--alias=480p  --format-sort=res:480,fps,ext:mp4,+vcodec:avc

--alias=en   "--no-write-auto-subs --write-subs --sub-langs='-all,en'"
--alias=it   "--no-write-auto-subs --write-subs --sub-langs='-all,it'"
--alias=no-embed "--no-embed-subs --no-embed-thumbnail"
--alias=private  "--no-cookies --impersonate=Chrome-110:Windows-10"
--alias=playlist "--output=~/video/%(playlist_title)s_by_%(playlist_channel)s/%(playlist_index)02d_%(title)s_[%(id|display_id|NA)s].%(ext)s"

# raiplay.it
--alias=rai-lo --format=hls-1365+hls-aac-Italiano
--alias=rai-mi --format=hls-2137+hls-aac-Italiano
--alias=rai-hi --format=hls-2793+hls-aac-Italiano

# f1tv.formula1.com
--alias=f1-path  "--paths home:~/video/formula1/{0}"
--alias=f1       "--abort-on-unavailable-fragments --format=3635+AUDIOGROUP-English --f1-path {0}"
