## hey emacs, this is kinda -*- sh -*- file
--cookies-from-browser=safari
--no-mtime
--no-playlist
--mark-watched
--write-subs
--sub-langs="-all,en,it"
--convert-subs=srt
--merge-output-format=mp4
--force-keyframes-at-cuts
--embed-chapters
--sponsorblock-mark=all
--fragment-retries=200
--retry-sleep=fragment:exp=1:256
--retry-sleep=extractor:linear=1:10
--output="%(title)s.%(ext)s"
--alias=-Q    --abort-on-unavailable-fragments
--alias=1080p --format-sort=res:1080,ext
--alias=720p  --format-sort=res:720,ext
--alias=480p  --format-sort=res:480,ext
--alias=download-auto-subs "--write-auto-subs --skip-download --ignore-errors"
